---
- function:
    name: FT_GetConfig()
    description: 获取力传感器配置
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0, company,device,softversion,bus],company:传感器厂商;失败：[errcode]

- function:
    name: FT_SetConfig(company,device,softversion,bus)
    description: 力传感器配置
    arguments:
      - name: company
        type: int
        description: 传感器厂商，17-坤维科技，19-航天十一院，20-ATI传感器，21-中科米点，22-伟航敏芯
      - name: device
        type: int
        description: 设备号，坤维(0-KWR75B)，航天十一院(0-MCS6A-200-4)，ATI(0-AXIA80-M8)，中科米点(0-MST2010)，伟航敏芯(0-WHC6L-YB-10A)
      - name: softversion
        type: int
        description: 软件版本号，暂不使用，默认为0
      - name: bus
        type: int
        description: 设备挂载末端总线位置，暂不使用，默认为0
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_Activate(state)
    description: 力传感器激活
    arguments:
      - name: state
        type: int
        description: 0-复位，1-激活
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_SetZero(state)
    description: 力传感器校零
    arguments:
      - name: state
        type: int
        description: 0-去除零点，1-零点矫正
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_SetRCS(ref)
    description: 设置力传感器参考坐标系
    arguments:
      - name: ref
        type: int
        description: 0-工具坐标系，1-基坐标系
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_PdIdenCompute()
    description: 负载重量辨识计算
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0,weight] ,weight-负载重量，单位kg;失败：[errcode]

- function:
    name: FT_PdIdenRecord(tool_id)
    description: 负载重量辨识记录
    arguments:
      - name: tool_id
        type: int
        description: 传感器坐标系编号，范围[0~14]
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_PdCogIdenCompute ()
    description: 负载质心辨识计算
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0,cog],cog=[cogx,cogy,cogz]，负载质心，单位mm;失败：[errcode]

- function:
    name: FT_PdCogIdenRecord(tool_id)
    description: 负载质心辨识记录
    arguments:
      - name: tool_id
        type: int
        description: 传感器坐标系编号，范围[0~14]
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_GetForceTorqueRCS()
    description: 获取参考坐标系下力/扭矩数据
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0,data] ,data=[fx,fy,fz,mx,my,mz];失败：[errcode]

- function:
    name: FT_GetForceTorqueOrigin()
    description: 获取力传感器原始力/扭矩数据
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0,data] ,data=[fx,fy,fz,mx,my,mz];失败：[errcode]

- function:
    name: FT_Guard(flag,sensor_num,select,force_torque,max_threshold,min_threshold)
    description: 碰撞守护
    arguments:
      - name: flag
        type: int
        description: 0-关闭碰撞守护，1-开启碰撞守护
      - name: sensor_num
        type: int
        description: 力传感器编号
      - name: select
        type: int
        description: 六个自由度是否检测碰撞[fx,fy,fz,mx,my,mz]，0-不生效，1-生效
      - name: force_torque
        type: float
        description: 碰撞检测力/力矩，单位N或Nm
      - name: max_threshold
        type: float
        description: 最大阈值
      - name: min_threshold
        type: float
        description: 最小阈值, 力/力矩检测范围为(force_torque-min_threshold,force_torque+max_threshold)
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_Control(flag,sensor_num,select,force_torque,gain,adj_sign,ILC_sign,max_dis,max_ang)
    description: 恒力控制
    arguments:
      - name: flag
        type: int
        description: 恒力控制开启标志，0-关，1-开
      - name: sensor_num
        type: int
        description: 力传感器编号
      - name: select
        type: int
        description: 六个自由度是否检测碰撞[fx,fy,fz,mx,my,mz]，0-不生效，1-生效
      - name: force_torque
        type: float
        description: 检测力/力矩，单位N或Nm
      - name: gain
        type: float
        description: 力、力矩PID参数，[f_p,f_i,f_d,m_p,m_i,m_d]
      - name: adj_sign
        type: int
        description: 自适应启停状态，0-关闭，1-开启
      - name: ILC_sign
        type: float
        description: ILC控制启停状态，0-停止，1-训练，2-实操
      - name: max_dis
        type: float
        description: 最大调整距离
      - name: max_ang
        type: float
        description: 最大调整角度
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_SpiralSearch(rcs,dr,fFinsih,t,vmax)
    description: 螺旋线探索
    arguments:
      - name: rcs
        type: int
        description: 参考坐标系，0-工具坐标系，1-基坐标系
      - name: dr
        type: float
        description: 每圈半径进给量，单位mm
      - name: fFinish
        type: float
        description: 力或力矩阈值(0~100)，单位N或Nm
      - name: t
        type: float
        description: 最大探索时间，单位ms
      - name: vmax
        type: float
        description: 线速度最大值，单位mm/s
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_RotInsertion(rcs,angVelRot,forceInsertion,angleMax,orn,angAccmax,rotorn)
    description: 旋转插入
    arguments:
      - name: rcs
        type: int
        description: 参考坐标系，0-工具坐标系，1-基坐标系
      - name: angVelRot
        type: float
        description: 旋转角速度，单位°/s
      - name: forceInsertion
        type: float
        description: 力或力矩阈值(0~100)，单位N或Nm
      - name: angleMax
        type: float
        description: 最大旋转角度，单位°
      - name: orn
        type: int
        description: 力的方向，1-fz,2-mz
      - name: angAccmax
        type: float
        description: 最大旋转加速度，单位°/s^2，暂不使用
      - name: rotorn
        type: int
        description: 旋转方向，1-顺时针，2-逆时针
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_LinInsertion(rcs,force_goal,lin_v,lin_a,disMax,linorn)
    description: 直线插入
    arguments:
      - name: rcs
        type: int
        description: 参考坐标系，0-工具坐标系，1-基坐标系
      - name: force_goal
        type: float
        description: 力或力矩阈值(0~100)，单位N或Nm
      - name: lin_v
        type: float
        description: 直线速度，单位mm/s
      - name: lin_a
        type: float
        description: 直线加速度，单位mm/s^2，暂不使用
      - name: disMax
        type: float
        description: 最大插入距离，单位mm
      - name: linorn
        type: int
        description: 插入方向，1-正方向，0-负方向
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_CalCenterStart()
    description: 计算中间平面位置开始
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_CalCenterEnd()
    description: 计算中间平面位置结束
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_FindSurface (rcs,dir,axis,lin_v,lin_a,disMax,force_goal)
    description: 表面定位
    arguments:
      - name: rcs
        type: int
        description: 参考坐标系，0-工具坐标系，1-基坐标系
      - name: dir
        type: int
        description: 移动方向，1-正方向，2-负方向
      - name: axis
        type: int
        description: 移动轴，1-x，2-y，3-z
      - name: lin_v
        type: float
        description: 探索直线速度，单位mm/s
      - name: lin_a
        type: float
        description: 探索直线加速度，单位mm/s^2
      - name: disMax
        type: float
        description: 最大探索距离，单位mm
      - name: force_goal
        type: float
        description: 动作终止力阈值，单位N
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_ComplianceStart(p,force)
    description: 柔顺控制开启
    arguments:
      - name: p
        type: float
        description: 位置调节系数或柔顺系数
      - name: force
        type: float
        description: 柔顺开启力阈值，单位N
    return: 成功：[0],失败：[errcode]

- function:
    name: FT_ComplianceStop()
    description: 柔顺控制关闭
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0],失败：[errcode]