---
- function:
    name: GetGripperConfig()
    description: 获取夹爪配置
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0, company,device,softversion,bus],company:夹爪厂商;失败：[errcode]

- function:
    name: ActGripper(index,action)
    description: 激活夹爪
    arguments:
      - name: index
        type: int
        description: 夹爪编号
      - name: action
        type: int
        description: 0-复位，1-激活
    return: 成功：[0],失败：[errcode]

- function:
    name: MoveGripper(index,pos,speed,force,maxtime,block)
    description: 控制夹爪
    arguments:
      - name: index
        type: int
        description: 夹爪编号
      - name: pos
        type: float
        description: 位置百分比，范围[0~100]
      - name: speed
        type: float
        description: 速度百分比，范围[0~100]
      - name: force
        type: float
        description: 力矩百分比，范围[0~100]
      - name: maxtime
        type: float
        description: 最大等待时间，范围[0~30000]，单位[ms]
      - name: block
        type: int
        description: 0-阻塞，1-非阻塞
    return: 成功：[0],失败：[errcode]    
  
- function:
    name: GetGripperMotionDone()
    description: 获取夹爪运动状态
    arguments:
      - name: n/a
        type: n/a
        description: n/a
    return: 成功：[0,status], status:0-运动未完成，1-运动完成;失败：[errcode]

- function:
    name: SetGripperConfig(company,device,softversion,bus)
    description: 配置夹爪
    arguments:
      - name: company
        type: int
        description: 夹爪厂商，1-Robotiq，2-慧灵，3-天机，4-大寰，5-知行
      - name: device
        type: int
        description: 设备号，Robotiq(0-2F-85系列)，慧灵(0-NK系列,1-Z-EFG-100)，天机(0-TEG-110)，大寰(0-PGI-140)，知行(0-CTPM2F20)
      - name: softversion
        type: int
        description: 软件版本号，暂不使用，默认为0
      - name: bus
        type: int
        description: 设备挂载末端总线位置，暂不使用，默认为0
    return: 成功：[0],失败：[errcode]
    
