---
- function:
    name: MoveL(joint_pos,desc_pos,tool,user,vel,acc,ovl,exaxis_pos,blendR,search,offset_flag,offset_pos)
    description: 笛卡尔空间直线运动
    arguments:
      - name: joint_pos
        type: float
        description: 目标关节位置，单位[°]
      - name: desc_pos
        type: float
        description: 目标笛卡尔位姿，单位[mm][°]
      - name: tool
        type: int
        description: 工具号，[0~14]
      - name: user
        type: int
        description: 工件号，[0~14]
      - name: vel
        type: float
        description: 速度百分比，[0~100]
      - name: acc
        type: float
        description: 加速度百分比，[0~100]，暂不开放
      - name: ovl
        type: float
        description: 速度缩放因子，[0~100]
      - name: exaxis_pos
        type: float
        description: 外部轴1位置~外部轴4位置,单位mm
      - name: blendR
        type: int
        description: 运动到位(阻塞)-[-1.0]，平滑时间(非阻塞)-[0~500]，单位[ms]
      - name: search
        type: int
        description: 不焊丝寻位-[0]，焊丝寻位-[1]
      - name: offset_flag
        type: int
        description: 不偏移-[0]，工件/基坐标系下偏移[1]，工具坐标系下偏移-[2]
      - name: offset_pos
        type: float
        description: 位姿偏移量，单位[mm][°]
    return: 成功：[0],失败：[errcode]

- function:
    name: MoveC(joint_pos_p,desc_pos_p,ptool,puser,pvel,pacc,exaxis_pos_p,poffset_flag,offset_pos_p,joint_pos_t,desc_pos_t,ttool,tuser,tvel,tacc,exaxis_pos_t ,toffset_flag,offset_pos_t,ovl,blendR)
    description: 笛卡尔空间圆弧运动
    arguments:
      - name: joint_pos_p
        type: float
        description: 路径点关节位置，单位[°]
      - name: desc_pos_p
        type: float
        description: 路径点笛卡尔位姿，单位[mm][°]
      - name: ptool
        type: int
        description: 工具号，[0~14]
      - name: puser
        type: int
        description: 工件号，[0~14]
      - name: pvel
        type: float
        description: 速度百分比，[0~100]
      - name: pacc
        type: float
        description: 加速度百分比，[0~100]，暂不开放
      - name: exaxis_pos_p
        type: float
        description: 外部轴1位置~外部轴4位置,单位mm
      - name: poffset_flag
        type: int
        description: 不偏移-[0]，工件/基坐标系下偏移-[1]，工具坐标系下偏移-[2]
      - name: offset_pos_p
        type: float
        description: 偏移量，单位[mm][°]
      - name: joint_pos_t
        type: float
        description: 目标点关节位置，单位[°]
      - name: desc_pos_t
        type: float
        description: 目标点笛卡尔位姿，单位[mm][°]
      - name: ttool
        type: int
        description: 工具号，[0~14][0]-不偏移，[1]-工件/基坐标系下偏移
      - name: tuser
        type: int
        description: 工件号，[0~14]
      - name: tvel
        type: float
        description: 速度百分比，[0~100]
      - name: tacc
        type: float
        description: 加速度百分比，[0~100]，暂不开放
      - name: exaxis_pos_t
        type: float
        description: 外部轴1位置~外部轴4位置
      - name: toffset_flag
        type: int
        description: 不偏移-[0]，工件/基坐标系下偏移-[1]，工具坐标系下偏移-[2]
      - name: offset_pos_t
        type: float
        description: 偏移量，单位[mm][°]
      - name: ovl
        type: float
        description: 速度缩放因子，[0~100]
      - name: blendR
        type: float
        description: 运动到位(阻塞)-[-1.0]，平滑半径(非阻塞)-[0~1000]，单位[mm]
    return: 成功：[0],失败：[errcode]

- function:
    name: Circle(joint_pos_p,desc_pos_p,ptool,puser,pvel,pacc,exaxis_pos_p,joint_pos_t,desc_pos_t,ttool,tuser,tvel,tacc,exaxis_pos_t,ovl,offset_flag,offset_pos)
    description: 笛卡尔空间整圆运动
    arguments:
      - name: joint_pos_p
        type: float
        description: 路径点关节位置，单位[°]
      - name: desc_pos_p
        type: float
        description: 路径点笛卡尔位姿，单位[mm][°]
      - name: ptool
        type: int
        description: 工具号，[0~14]
      - name: puser
        type: int
        description: 工件号，[0~14]
      - name: pvel
        type: float
        description: 速度百分比，[0~100]
      - name: pacc
        type: float
        description: 加速度百分比，[0~100]，暂不开放
      - name: exaxis_pos_p
        type: float
        description: 外部轴1位置~外部轴4位置,单位mm
      - name: joint_pos_t
        type: float
        description: 目标点关节位置，单位[°]
      - name: desc_pos_t
        type: float
        description: 目标点笛卡尔位姿，单位[mm][°]
      - name: ttool
        type: int
        description: 工具号，[0~14]
      - name: tuser
        type: int
        description: 工件号，[0~14]
      - name: tvel
        type: float
        description: 速度百分比，[0~100]
      - name: tacc
        type: float
        description: 加速度百分比，[0~100]，暂不开放
      - name: exaxis_pos_t
        type: float
        description: 外部轴1位置~外部轴4位置
      - name: ovl
        type: float
        description: 速度缩放因子，[0~100]
      - name: offset_flag
        type: int
        description: 不偏移-[0]，工件/基坐标系下偏移-[1]，工具坐标系下偏移-[2]
      - name: offset_pos
        type: float
        description: 偏移量，单位[mm][°]
    return: 成功：[0],失败：[errcode]

- function:
    name: NewSpiral(joint_pos,desc_pos,tool,user,vel,acc,exaxis_pos,ovl,offset_flag,offset_pos,param)
    description: 笛卡尔空间螺旋线运动
    arguments:
      - name: joint_pos
        type: float
        description: 目标关节位置，单位[°]
      - name: desc_pos
        type: float
        description: 目标笛卡尔位姿，单位[mm][°]
      - name: tool
        type: int
        description: 工具号，[0~14]
      - name: user
        type: int
        description: 工件号，[0~14]
      - name: vel
        type: float
        description: 速度百分比，[0~100]
      - name: acc
        type: float
        description: 加速度百分比，[0~100]，暂不开放
      - name: exaxis_pos
        type: float
        description: 外部轴1位置~外部轴4位置,单位mm
      - name: ovl
        type: float
        description: 速度缩放因子，[0~100]
      - name: offset_flag
        type: int
        description: 不偏移-[0]，工件/基坐标系下偏移-[1]，工具坐标系下偏移-[2]
      - name: offset_pos
        type: float
        description: 位姿偏移量，单位[mm][°]
      - name: param
        type: list
        description: 列表[circle_num,circle_angle,rad_init,rad_add,rotaxis_add,rot_direction]，其中circle_num:螺旋圈数，circle_angle:螺旋倾角，rad_init:螺旋初始半径，rad_add:半径增量，rotaxis_add:转轴方向增量，rot_direction:旋转方向，0-顺时针，1-逆时针
    return: 成功：[0],失败：[errcode]
- function:
    name: ServoCart(mode,desc_pos,pos_gain,acc,vel,cmdT,filterT,gain)
    description: 笛卡尔空间伺服模式运动
    arguments:
      - name: mode
        type: int
        description: 绝对运动(基坐标系)-[0]，增量运动(基坐标系)-[1]，增量运动(工具坐标系)-[2]
      - name: desc_pos
        type: float
        description: 目标笛卡尔位置/目标笛卡尔位置增量
      - name: pos_gain
        type: float
        description: 位姿增量比例系数，仅在增量运动下生效，范围[0~1]
      - name: acc
        type: float
        description: 加速度，范围[0~100]，暂不开放，默认为0
      - name: vel
        type: float
        description: 速度，范围[0~100]，暂不开放，默认为0
      - name: cmdT
        type: float
        description: 指令周期，单位[s]，[0.001~0.016]
      - name: filterT
        type: float
        description: 滤波时间，单位[s]，暂不开放
      - name: gain
        type: float
        description: 目标位置的比例放大器，暂不开放
    return: 成功：[0],失败：[errcode]

- function:
    name: MoveCart(desc_pos,tool,user,vel,acc,ovl,blendT,config)
    description: 笛卡尔空间点到点运动
    arguments:
      - name: desc_pos
        type: float
        description: 目标笛卡尔位置
      - name: tool
        type: int
        description: 工具号，[0~14]
      - name: user
        type: int
        description: 工件号，[0~14]
      - name: vel
        type: float
        description: 速度，范围[0~100]，暂不开放，默认为0
      - name: acc
        type: float
        description: 加速度，范围[0~100]，暂不开放，默认为0
      - name: ovl
        type: float
        description: 速度缩放因子，[0~100]
      - name: blendT
        type: float
        description: 运动到位(阻塞)-[-1.0]，平滑时间(非阻塞)-[0~500]，单位[ms]
      - name: config
        type: int
        description: 关节配置，[-1]-参考当前关节位置求解，[0~7]-依据关节配置求解
    return: 成功：[0],失败：[errcode]