---
- function:
    name: MoveJ(joint_pos,desc_pos,tool,user,vel,acc,ovl,exaxis_pos,blendT,offset_flag,offset_pos)
    description: 关节空间运动
    arguments:
      - name: joint_pos
        type: float
        description: 目标关节位置，单位[°]
      - name: desc_pos
        type: float
        description: 目标笛卡尔位姿，单位[mm][°]
      - name: tool
        type: int
        description: 工具号，[0~14]
      - name: user
        type: int
        description: 工件号，[0~14]
      - name: vel
        type: float
        description: 速度百分比，[0~100]
      - name: acc
        type: float
        description: 加速度百分比，[0~100]，暂不开放
      - name: ovl
        type: float
        description: 速度缩放因子，[0~100]
      - name: exaxis_pos
        type: float
        description: 外部轴1位置~外部轴4位置,单位mm
      - name: blendT
        type: int
        description: 运动到位(阻塞)-[-1.0]，平滑时间(非阻塞)-[0~500]，单位[ms]
      - name: offset_flag
        type: int
        description: 不偏移-[0]，工件/基坐标系下偏移-[1]，工具坐标系下偏移-[2]
      - name: offset_pos
        type: float
        description: 位姿偏移量，单位[mm][°]
    return: 成功：[0],失败：[errcode]
  
- function:
    name: ServoJ(joint_pos,acc,vel,cmdT,filterT,gain)
    description: 关节空间伺服模式运动
    arguments:
      - name: joint_pos
        type: float
        description: 目标关节位置，单位[°]
      - name: acc
        type: float
        description: 加速度，范围[0~100]，暂不开放，默认为0
      - name: vel
        type: float
        description: 速度，范围[0~100]，暂不开放，默认为0
      - name: cmdT
        type: float
        description: 指令周期，单位[s]，[0.001~0.016]
      - name: filterT
        type: float
        description: 滤波时间，单位[s]，暂不开放
      - name: gain
        type: float
        description: 目标位置的比例放大器，暂不开放
    return: 成功：[0],失败：[errcode]